### ISSUE TITLE
Allow modification of string delimiters

### ISSUE THREAD

**Issue by bbamsch** [Linesmerrill/atom-mocha-snippets#3]
Snippets assume that double quotation (") delimiter is used for strings but single quotation.

Some projects, notably those following the [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes) follow single quote delimited strings.

Plugin should allow the user to configure the string delimiter used for snippets.

**Comment by Linesmerrill** [comment]
Hi Brian, 

Thanks for your interest in this plugin. I agree with you that having a setting to allow the user to toggle between using either the single or double quotes would be super fantastic. I am accepting pull requests, so if you would like to research, or know how to add a settings option to a package in atom please let me know. 

Cheers,

Merrill

**Comment by bbamsch** [comment]
Adding a package setting is fairly easy. However, after a bit of searching I can't find any way to control snippets programmatically from the settings. If I do find a way, I'll put together a patch but I suspect I won't be digging further into finding a solution to this anytime soon.

**Comment by Linesmerrill** [comment]
@bbamsch,

I have some great news for you! After your great suggestion and with the help of @thoiberg the latest version now supports users to modify the settings for quotes as well as semicolons. Default will be single quotes and then the user can modify them to be double if needed.

This does require a full restart of atom in order for the settings to take effect, but I am happy to say that the issue has been resolved!

Thank you for your input!

Cheers,

Merrill Lines

**Comment by bbamsch** [comment]
Great to hear! Nice work @thoiberg
