### ISSUE TITLE
support for using single quote

### ISSUE THREAD

**Issue by harryi3t** [Linesmerrill/atom-mocha-snippets#4]
our coding standard requires allowing only single quotes in js files.
Can it be possible to have a setting for this?
When checked all auto-complete will use single quotes.

### from 
```
describe("", function(){

});
```

### to
```js
describe('', function(){

});
```

**Comment by Linesmerrill** [comment]
Hi @harryi3t,

Thank you for your comment and want to use this snippet generator! This has been a big discussion topic with many users and I am currently looking into how to change this for you. 

What I may end up doing is releasing another snippet generator that would only use single quotes. The problem I currently am facing with allowing the user to specify which to use (i.e. single quotes vs double quotes) is that I have no way of introducing settings into a snippet. 

Cheers,

Merrill Lines

**Comment by Linesmerrill** [comment]
@harryi3t,

I have some great news for you! After your great suggestion and with the help of @thoiberg the latest version now supports users to modify the settings for quotes as well as semicolons. Default will be single quotes and then the user can modify them to be double if needed. 

This does require a full restart of atom in order for the settings to take effect, but I am happy to say that the issue has been resolved!

Thank you for your input!

Cheers,

Merrill Lines

**Comment by harryi3t** [comment]
just tried, works as expected
now it even uses arrow functions :+1:  , that awesome! thanks
![image](https://cloud.githubusercontent.com/assets/5207331/25424722/081deffa-2a87-11e7-9d51-6f80ab31bc4e.png)

**Comment by Linesmerrill** [comment]
Awesome! Thank you for continuing to use the plugin! Please share with your friends and co workers.
